name: Build PDF

on:
  push:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      WORKDIR: ${{ vars.PROJECT_TO_BUILD }}
      REPOSITORY: ${{ github.repository }}
      REPO_NAME: ${{ github.event.repository.name }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Get commit info
        id: commit
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT

      - name: Compile LaTeX document
        if: ${{ env.WORKDIR != '' }}
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          working_directory: ${{ env.WORKDIR }}

      - name: Upload PDF file
        if: ${{ env.WORKDIR != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: ${{ env.WORKDIR }}/main.pdf


      - name: Send PDF to Discord
        if: ${{ env.WORKDIR != '' && env.DISCORD_WEBHOOK != '' }}
        env:
          DISCORD_WEBHOOK: ${{ env.DISCORD_WEBHOOK }}
          WORKDIR: ${{ env.WORKDIR }}
          COMMIT_MESSAGE: ${{ steps.commit.outputs.message }}
          COMMIT_AUTHOR: ${{ steps.commit.outputs.author }}
          REPOSITORY: ${{ env.REPOSITORY }}
          REPO_NAME: ${{ env.REPO_NAME }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          CONTENT=$(jq -n --arg repo "$REPO_NAME" --arg wdir "$WORKDIR" --arg author "$COMMIT_AUTHOR" --arg msg "$COMMIT_MESSAGE" --arg branch "$BRANCH_NAME" \
            '{content: "# ðŸ“˜ **\($repo)**\n- Built **\($wdir)/main.tex** from branch `\($branch)`\nðŸ§¾ Last Commit by **\($author)**:\n```\n\($msg)\n```"}')
          curl -F "payload_json=${CONTENT}" \
               -F "file=@${WORKDIR}/main.pdf" \
               "$DISCORD_WEBHOOK"
